/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingSucessoRouteImport } from './routes/briefing.sucesso'

const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingSucessoRoute = BriefingSucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => BriefingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRouteWithChildren
  '/briefing/sucesso': typeof BriefingSucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRouteWithChildren
  '/briefing/sucesso': typeof BriefingSucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/briefing': typeof BriefingRouteWithChildren
  '/briefing/sucesso': typeof BriefingSucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/briefing' | '/briefing/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/briefing' | '/briefing/sucesso'
  id: '__root__' | '/' | '/auth' | '/briefing' | '/briefing/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BriefingRoute: typeof BriefingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/sucesso': {
      id: '/briefing/sucesso'
      path: '/sucesso'
      fullPath: '/briefing/sucesso'
      preLoaderRoute: typeof BriefingSucessoRouteImport
      parentRoute: typeof BriefingRoute
    }
  }
}

interface BriefingRouteChildren {
  BriefingSucessoRoute: typeof BriefingSucessoRoute
}

const BriefingRouteChildren: BriefingRouteChildren = {
  BriefingSucessoRoute: BriefingSucessoRoute,
}

const BriefingRouteWithChildren = BriefingRoute._addFileChildren(
  BriefingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BriefingRoute: BriefingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
